name: Build & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install deps and build package
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm coverage 
