name: Node.js Package
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*"

jobs:
  publish:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v6
        with:
          node-version: 24.11.0
          registry-url: "https://npm.pkg.github.com"
          cache: npm
      - run: npm ci
      - run: npm run typecheck
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
